import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const DJ_NAME = process.env.NEXT_PUBLIC_DJ_NAME ?? "DJ MC";
const SITE_URL =
  process.env.NEXT_PUBLIC_SITE_URL ?? "https://kara.ftrai.uk";

const SITE_TITLE = `Karaoke Night with ${DJ_NAME}`;
const SITE_DESCRIPTION = `Self-serve karaoke sign-ups. Scan the QR, drop your song, watch your setlist update live. Hosted by ${DJ_NAME}.`;

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: SITE_TITLE,
    template: `%s · ${DJ_NAME} Karaoke`,
  },
  description: SITE_DESCRIPTION,
  applicationName: `${DJ_NAME} Karaoke`,
  authors: [{ name: DJ_NAME }],
  keywords: ["karaoke", "DJ", DJ_NAME, "live sign-up", "queue"],
  openGraph: {
    type: "website",
    url: SITE_URL,
    siteName: `${DJ_NAME} Karaoke`,
    title: SITE_TITLE,
    description: SITE_DESCRIPTION,
    // og:image is generated by app/opengraph-image.tsx (1200×630 PNG)
    // and auto-injected by Next.js's file convention.
  },
  twitter: {
    card: "summary_large_image",
    title: SITE_TITLE,
    description: SITE_DESCRIPTION,
    // twitter:image inherits from the opengraph-image file convention.
  },
  appleWebApp: {
    capable: true,
    title: `${DJ_NAME} Karaoke`,
    statusBarStyle: "black-translucent",
  },
  formatDetection: {
    telephone: false,
  },
  robots: {
    index: true,
    follow: true,
  },
};

export const viewport: Viewport = {
  themeColor: "#581c87", // purple-900, matches the splash gradient base
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
